### ISSUE TITLE
LED Light Bulb

### ISSUE THREAD

**Issue by pickeld** [Theb-1/ESP8266-wifi-light-dimmer#3]
hey, i must ask, what i takes to dim a LED light bulb?
will this solution work?
are there any specific LED Light bulbe that will work?
thank you

**Comment by Theb-1** [comment]
Any LED bulb that is labeled as "dimmable" should work with this circuit. I am currently using dimmable LED bulbs with this.

**Comment by pickeld** [comment]
Such good news! Can you share a link for your LED lights? Thank you!

**Comment by Theb-1** [comment]
I usually purchase mine from Walmart when they go on sale.

I primarily use these for daylight:
https://www.walmart.com/ip/Great-Value-LED-Light-Bulb-10W-60W-Equivalent-Omni-E26-Dimmable-Daylight/38591215

And these for soft:
https://www.walmart.com/ip/Great-Value-LED-Light-Bulb-10W-60W-Equivalent-Omni-E26-Dimmable-Soft-White/38591217

**Comment by pickeld** [comment]
Thank you very much. Can confirm that its working. :)
