### ISSUE TITLE
Configuration (brightness value) not getting saved after sending command via HTTP 

### ISSUE THREAD

**Issue by srijansaxena11** [Theb-1/ESP8266-wifi-light-dimmer#6]
After connecting my AC Dimmer with wemos mini I am unable to save the configuration via HTTP GET command. I tried using this: 192.168.0.x/?b=0
This makes the output voltage to drop and then it rises again and when I open the page 192.168.0.x to check the configuration it shows b=255. Which means it is not getting saved. Any ideas?

**Comment by Theb-1** [comment]
Try setting buttonActiveOn = 1 at the top under the button settings section. Depending on how this is set and your pullup/pulldown button configuration, it may think you're holding down the button, which will quickly increase the brightness until it reaches 255 again.

**Comment by srijansaxena11** [comment]
I just removed the buttons part and configured it according to my needs and its working... thank you anyway for replying
